app:
    authentication:
        headerType: X-AUTH-TOKEN
spring:
    profiles:
        active: development
    data:
        rest:
            base-path: /api
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            naming:
                implicit-strategy: com.trinjer.configuration.persistence.strategy.TrinjerImplicitNamingStrategy
                physical-strategy: com.trinjer.configuration.persistence.strategy.TrinjerPhysicalNamingStrategy