spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/trinjer
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
server:
    port: 9000